name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Goodstack tests
      run: npm run test:goodstack
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: goodstack-test-reports
        path: goodstack/test-reports/
        retention-days: 3
    - name: Run new site tests
      run: npm run test:newsite
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: new-site-test-reports
        path: new-site/test-reports/
        retention-days: 3
